name: Mirror Branch

on:
  push:
    branches:
      - oldpower

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Sync changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Fetch and checkout the mirror branch
          git fetch origin power
          git checkout power
          git merge origin/power

          # Pull changes from the source repository
          git pull https://github.com/ghost8658private/ttesting.git power

          # Push changes to the mirror branch
          git push origin power

      - name: Cleanup
        run: |
          cd ..
          rm -rf destination-repo
