name: Tclone Mirror-Remote

on:
    push:
    workflow_dispatch:


jobs:
    mirror_branch:
        uses: ghost8658private/tclone/.github/workflows/tclone.yml@case
        with:
            upstream-repo: ghost8658private/ttesting.git
            main-repo: ghost8658private/tclone.git
            #branches: main:main
        secrets:
            ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}
            SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}